schedule:
  interval_minutes: 1

gitrepo_path:
  repo1:
    path: "./test"
    compose_path: "./test/docker-compose.yml"

  repo2:
    path: "./taskrepo"
    compose_path: "./taskrepo/docker-compose.yaml"

Success_condition:
  keywords:
    - "!error"
    - "!failed"
    - "!fail"
    - "!exception"
    - "!unexpected"
    - "!abort"
    - "!fatal"
    - "!container_error"
    - "!service_failed"
    - "!network_error"
    

exception_condition:
  - search:
      keywords:
        - "docker login"
        - "denied"
    command: "docker run --rm -i public.ecr.aws/aws-cli/aws-cli ecr get-login-password --region eu-west-3 | docker login -u AWS --password-stdin 880947752174.dkr.ecr.eu-west-3.amazonaws.com"
  - search:
      keywords:
        - "space"
    command: "docker system prune -af"
