version: '3.8'
services:
  autodeploy:
    build:
      context: .
      dockerfile: Dockerfile.autodeploy
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/water/tmp/autodeploy/:/app/
    ports:
      - "80:80"
    environment:
      DOCKER_TLS_CERTDIR: ""
    restart: always
