version: '3.8'
services:
  autodeploy:
    build:
      context: .
      dockerfile: Dockerfile.autodeploy
    #privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/water/tmp/AutomatComposeDeploy/autodeploy:/app/autodeploy  # Specify the full path to the `autodeploy` directory of Host.
    #ports:
    #environment:
    restart: always
